import type { Metadata } from "next";
import "./globals.css";
import { lexendExa } from "./typescript/css_constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendExa.variable} overflow-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
